# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute
test_manuel:
    path: /test
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController

# Si vous utilisez des bundles (ex: EasyAdmin), ajoutez leurs imports ici
# easy_admin_bundle:
#     resource: '@EasyAdminBundle/Resources/config/routes.yaml'