# config/services.yaml

parameters:
    # Emails phishing
    mailer.phishing.boa: '%env(MAILER_PHISHING_BOA)%'
    mailer.phishing.sbee: '%env(MAILER_PHISHING_SBEE)%'
    mailer.phishing.unicef: '%env(MAILER_PHISHING_UNICEF)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'